"""Prompts package for managing AI prompts"""

from .manager import PromptManager
from .base import (
    MAIN_SYSTEM_PROMPT,
    HIGHLIGHT_SYSTEM_PROMPT,
    HIGHLIGHT_QUESTION_SYSTEM_PROMPT,
    SUMMARY_SYSTEM_PROMPT,
    MAIN_USER_PROMPT,
    HIGHLIGHT_USER_PROMPT,
    HIGHLIGHT_QUESTION_USER_PROMPT,
    MAIN_QUESTION_USER_PROMPT,
    SUMMARY_USER_PROMPT
)

__all__ = [
    'PromptManager',
    # System prompts
    'MAIN_SYSTEM_PROMPT',
    'HIGHLIGHT_SYSTEM_PROMPT',
    'HIGHLIGHT_QUESTION_SYSTEM_PROMPT',
    'SUMMARY_SYSTEM_PROMPT',
    # User prompts
    'MAIN_USER_PROMPT',
    'HIGHLIGHT_USER_PROMPT',
    'HIGHLIGHT_QUESTION_USER_PROMPT',
    'MAIN_QUESTION_USER_PROMPT',
    'SUMMARY_USER_PROMPT'
]
